[target.i686-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "panic=abort",
    "-C", "relocation-model=static",
    # Эта строка отключает тот самый вредный флаг:
    "-C", "link-args=-Wl,--no-eh-frame-hdr", 
]

[build]
target = "i686-unknown-linux-gnu"
