[target.i686-unknown-linux-gnu]
# Указываем использовать встроенный линковщик LLD
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "panic=abort",
    # Явно указываем flavor для линковщика
    "-C", "linker-flavor=ld.lld",
]

[build]
target = "i686-unknown-linux-gnu"
